---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: psp-test
  name: psp-test


# Below cronjob prints hello every minute
--- 
apiVersion: batch/v1
kind: CronJob
metadata:
  name: psp-test
  namespace: psp-test
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            securityContext:
              privileged: true
              allowPrivilegeEscalation: true
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure

