---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: psp-test
  name: restrictive-ns

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: restrictive-sa
  namespace: restrictive-ns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restrictive-rb
  namespace: restrictive-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:restrictive
subjects:
- kind: ServiceAccount
  name: restrictive-sa
  namespace: restrictive-ns

---
# Below cronjob prints hello every minute
--- 
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restrictive-cron
  namespace: restrictive-ns
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: restrictive-sa
          containers:
          - name: hello
            image: busybox:1.28
            securityContext:
              privileged: true
              allowPrivilegeEscalation: true
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure

